#!/usr/bin/env python3
import re
from pathlib import Path


DUMP_PATH = Path("/Users/kms/Downloads/sangol/SANGOL_PHP/ikor250911t-20260409.dump")
OUT_SQL_PATH = Path("/Users/kms/Downloads/sangol/backend/database/postgres/legacy_seed_v1.sql")

PRODUCT_TABLE_CATEGORY = {
    "g5_write_product1": "임산물",
    "g5_write_product2": "농산물",
    "g5_write_product3": "제품",
}

PRODUCT_TABLE_PREFIX = {
    "g5_write_product1": "IM",
    "g5_write_product2": "AG",
    "g5_write_product3": "PR",
}


def is_zero_datetime(value: str) -> bool:
    return value in ("0000-00-00 00:00:00", "0000-00-00", "")


def parse_sql_string(token: str):
    token = token.strip()
    if token.upper() == "NULL":
        return None
    if token.startswith("'") and token.endswith("'"):
        inner = token[1:-1]
        inner = inner.replace("\\\\", "\\")
        inner = inner.replace("\\'", "'")
        inner = inner.replace("\\r", "\r")
        inner = inner.replace("\\n", "\n")
        return inner
    return token


def parse_values_segment(segment: str):
    rows = []
    i = 0
    n = len(segment)
    while i < n:
        if segment[i] != "(":
            i += 1
            continue
        i += 1
        values = []
        cur = []
        in_str = False
        esc = False
        depth = 1
        while i < n and depth > 0:
            ch = segment[i]
            if in_str:
                cur.append(ch)
                if esc:
                    esc = False
                elif ch == "\\":
                    esc = True
                elif ch == "'":
                    in_str = False
            else:
                if ch == "'":
                    in_str = True
                    cur.append(ch)
                elif ch == "(":
                    depth += 1
                    cur.append(ch)
                elif ch == ")":
                    depth -= 1
                    if depth == 0:
                        token = "".join(cur).strip()
                        if token:
                            values.append(parse_sql_string(token))
                        break
                    cur.append(ch)
                elif ch == "," and depth == 1:
                    token = "".join(cur).strip()
                    values.append(parse_sql_string(token))
                    cur = []
                else:
                    cur.append(ch)
            i += 1
        rows.append(values)
        i += 1
    return rows


def sql_quote(value):
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return str(value)
    s = str(value).replace("'", "''")
    return f"'{s}'"


def extract_first_img_src(html: str):
    if not html:
        return None
    m = re.search(r'<img[^>]+src="([^"]+)"', html, re.IGNORECASE)
    return m.group(1) if m else None


def build_sql():
    member_rows = []
    product_rows = []
    notice_rows = []
    inquiry_rows = []

    with DUMP_PATH.open("r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            if not line.startswith("INSERT INTO `"):
                continue
            if line.startswith("INSERT INTO `g5_member`"):
                data = parse_values_segment(line[line.index("VALUES") + 6 :])
                member_rows.extend(data)
            elif any(line.startswith(f"INSERT INTO `{t}`") for t in PRODUCT_TABLE_CATEGORY):
                table_name = line.split("`")[1]
                data = parse_values_segment(line[line.index("VALUES") + 6 :])
                for row in data:
                    product_rows.append((table_name, row))
            elif line.startswith("INSERT INTO `g5_write_notice`"):
                notice_rows.extend(parse_values_segment(line[line.index("VALUES") + 6 :]))
            elif line.startswith("INSERT INTO `g5_write_inquiry`"):
                inquiry_rows.extend(parse_values_segment(line[line.index("VALUES") + 6 :]))

    sql_lines = [
        "-- Generated by build_legacy_seed_v1.py",
        "-- Source: SANGOL_PHP/ikor250911t-20260409.dump",
        "BEGIN;",
        "",
    ]

    # Users (minimal migration)
    sql_lines.append("-- users: g5_member -> users")
    for row in member_rows:
        # g5_member indexes
        mb_id = row[1] or ""
        mb_password = row[2] or ""
        mb_name = row[4] or mb_id
        mb_email = row[7] or f"{mb_id}@legacy.local"
        mb_level = int(row[9] or 0)
        mb_leave_date = row[30] or ""
        mb_datetime = row[28] or ""
        mb_today_login = row[26] or ""

        role = "admin" if (mb_id == "admin" or mb_level >= 10) else "customer"
        is_active = not bool(mb_leave_date)
        created_at = None if is_zero_datetime(mb_datetime) else mb_datetime
        updated_at = None if is_zero_datetime(mb_today_login) else mb_today_login

        sql_lines.append(
            "INSERT INTO users (email, password, name, role, franchise_id, is_active, created_at, updated_at) "
            f"VALUES ({sql_quote(mb_email)}, {sql_quote(mb_password)}, {sql_quote(mb_name)}, {sql_quote(role)}, NULL, {sql_quote(is_active)}, "
            f"COALESCE({sql_quote(created_at)}::timestamptz, NOW()), COALESCE({sql_quote(updated_at)}::timestamptz, NOW())) "
            "ON CONFLICT (email) DO UPDATE SET "
            "password = EXCLUDED.password, name = EXCLUDED.name, role = EXCLUDED.role, is_active = EXCLUDED.is_active, updated_at = NOW();"
        )
    sql_lines.append("")

    # Products
    sql_lines.append("-- products: g5_write_product1/2/3 -> products")
    for table_name, row in product_rows:
        wr_id = row[0]
        ca_name = row[7] or ""
        wr_subject = row[9] or ""
        wr_content = row[10] or ""
        wr_datetime = row[24] or ""
        wr_last = row[26] or ""
        wr_1 = row[30] or ""

        # 신규 시스템 표준 코드 우선:
        # 1) 레거시 wr_1 값이 있으면 정제해서 사용
        # 2) 없으면 신규 Prefix 기반 코드(SG-IM/AG/PR-XXXX) 생성
        raw_code = wr_1.strip()
        if raw_code:
            product_code = re.sub(r"[^A-Za-z0-9_-]", "-", raw_code).strip("-")
        else:
            product_code = f"SG-{PRODUCT_TABLE_PREFIX[table_name]}-{int(wr_id):04d}"
        category = PRODUCT_TABLE_CATEGORY[table_name]
        if ca_name.strip():
            category = ca_name.strip()
        image_url = extract_first_img_src(wr_content)
        created_at = None if is_zero_datetime(wr_datetime) else wr_datetime
        updated_at = None if is_zero_datetime(wr_last) else wr_last

        sql_lines.append(
            "INSERT INTO products (product_code, name, category, description, unit, tax_type, cost_price, price, image_url, is_active, stock_status, created_at, updated_at) "
            f"VALUES ({sql_quote(product_code)}, {sql_quote(wr_subject)}, {sql_quote(category)}, {sql_quote(wr_content)}, "
            "'1kg', 'taxable', NULL, 0, "
            f"{sql_quote(image_url)}, TRUE, 'in_stock', COALESCE({sql_quote(created_at)}::timestamptz, NOW()), COALESCE({sql_quote(updated_at)}::timestamptz, NOW())) "
            "ON CONFLICT (product_code) DO UPDATE SET "
            "name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, "
            "image_url = EXCLUDED.image_url, updated_at = NOW();"
        )
    sql_lines.append("")

    # Notices
    sql_lines.append("-- notices: g5_write_notice -> notices")
    if notice_rows:
        for row in notice_rows:
            title = row[9] or ""
            content = row[10] or ""
            wr_hit = int(row[16] or 0)
            author = (row[21] or "").strip() or (row[19] or "").strip() or "legacy"
            wr_datetime = row[24] or ""
            wr_last = row[26] or ""
            created_at = None if is_zero_datetime(wr_datetime) else wr_datetime
            updated_at = None if is_zero_datetime(wr_last) else wr_last
            sql_lines.append(
                "INSERT INTO notices (title, content, author, views, is_active, created_at, updated_at) "
                f"VALUES ({sql_quote(title)}, {sql_quote(content)}, {sql_quote(author)}, {wr_hit}, TRUE, "
                f"COALESCE({sql_quote(created_at)}::timestamptz, NOW()), COALESCE({sql_quote(updated_at)}::timestamptz, NOW()));"
            )
    else:
        sql_lines.append("-- no notice rows found in dump")
    sql_lines.append("")

    # Inquiries
    sql_lines.append("-- inquiries: g5_write_inquiry -> inquiries")
    if inquiry_rows:
        for row in inquiry_rows:
            name = (row[21] or "").strip() or "이름없음"
            email = (row[22] or "").strip() or "unknown@legacy.local"
            subject = (row[9] or "").strip() or "(제목없음)"
            message = row[10] or ""
            phone = (row[30] or "").strip() or "미입력"
            wr_datetime = row[24] or ""
            wr_last = row[26] or ""
            created_at = None if is_zero_datetime(wr_datetime) else wr_datetime
            updated_at = None if is_zero_datetime(wr_last) else wr_last
            sql_lines.append(
                "INSERT INTO inquiries (name, email, phone, subject, message, status, response, created_at, updated_at) "
                f"VALUES ({sql_quote(name)}, {sql_quote(email)}, {sql_quote(phone)}, {sql_quote(subject)}, {sql_quote(message)}, "
                f"'pending', NULL, COALESCE({sql_quote(created_at)}::timestamptz, NOW()), COALESCE({sql_quote(updated_at)}::timestamptz, NOW()));"
            )
    else:
        sql_lines.append("-- no inquiry rows found in dump")
    sql_lines.append("")

    sql_lines.append("COMMIT;")

    OUT_SQL_PATH.write_text("\n".join(sql_lines), encoding="utf-8")
    return {
        "member_rows": len(member_rows),
        "product_rows": len(product_rows),
        "notice_rows": len(notice_rows),
        "inquiry_rows": len(inquiry_rows),
    }


if __name__ == "__main__":
    stats = build_sql()
    print(f"Generated: {OUT_SQL_PATH}")
    print(stats)
